# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\loginscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
import sys


class Ui_LogInterface(object):
    def setupUi(self, LogInterface):
        LogInterface.setObjectName("LogInterface")
        LogInterface.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(LogInterface)
        self.centralwidget.setObjectName("centralwidget")
        self.username = QtWidgets.QLabel(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(40, 50, 61, 31))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLabel(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(40, 100, 61, 31))
        self.password.setObjectName("password")
        self.unenter = QtWidgets.QLineEdit(self.centralwidget)
        self.unenter.setGeometry(QtCore.QRect(110, 60, 113, 20))
        self.unenter.setObjectName("unenter")
        self.pwenter = QtWidgets.QLineEdit(self.centralwidget)
        self.pwenter.setGeometry(QtCore.QRect(110, 110, 113, 20))
        self.pwenter.setObjectName("pwenter")
        self.loginbttn = QtWidgets.QPushButton(self.centralwidget)
        self.loginbttn.setGeometry(QtCore.QRect(110, 160, 111, 41))
        self.loginbttn.setObjectName("loginbttn")
        self.loginbttn.clicked.connect()
        self.createlabel = QtWidgets.QLabel(self.centralwidget)
        self.createlabel.setGeometry(QtCore.QRect(380, 10, 241, 31))
        self.createlabel.setObjectName("createlabel")
        self.userlabel = QtWidgets.QLabel(self.centralwidget)
        self.userlabel.setGeometry(QtCore.QRect(10, 10, 291, 31))
        self.userlabel.setObjectName("userlabel")
        self.newun = QtWidgets.QLabel(self.centralwidget)
        self.newun.setGeometry(QtCore.QRect(280, 50, 81, 31))
        self.newun.setObjectName("newun")
        self.newpw = QtWidgets.QLabel(self.centralwidget)
        self.newpw.setGeometry(QtCore.QRect(280, 100, 81, 31))
        self.newpw.setObjectName("newpw")
        self.newpwenter = QtWidgets.QLineEdit(self.centralwidget)
        self.newpwenter.setGeometry(QtCore.QRect(390, 110, 113, 20))
        self.newpwenter.setObjectName("newpwenter")
        self.newunenter = QtWidgets.QLineEdit(self.centralwidget)
        self.newunenter.setGeometry(QtCore.QRect(390, 60, 113, 20))
        self.newunenter.setObjectName("newunenter")
        self.registerbtn = QtWidgets.QPushButton(self.centralwidget)
        self.registerbtn.setGeometry(QtCore.QRect(390, 160, 111, 41))
        self.registerbtn.setObjectName("registerbtn")
        LogInterface.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LogInterface)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        LogInterface.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LogInterface)
        self.statusbar.setObjectName("statusbar")
        LogInterface.setStatusBar(self.statusbar)

        self.retranslateUi(LogInterface)
        QtCore.QMetaObject.connectSlotsByName(LogInterface)
    
    def login(self):
        try:
            email=self.unenter.text()
            password=self.pwenter.text()

            mydb=mc.connect(
                host="localhost",
                user="root",
                password="Efehan33!",
                database="libraryprogram"
            )
            
        except mc.Error as Error_01:


    def retranslateUi(self, LogInterface):
        _translate = QtCore.QCoreApplication.translate
        LogInterface.setWindowTitle(_translate("LogInterface", "MainWindow"))
        self.username.setText(_translate("LogInterface", "Username:"))
        self.password.setText(_translate("LogInterface", "Password:"))
        self.loginbttn.setText(_translate("LogInterface", "Login "))
        self.createlabel.setText(_translate("LogInterface", "Create an account if you don\'t have"))
        self.userlabel.setText(_translate("LogInterface", "If you have an account enter your username and password"))
        self.newun.setText(_translate("LogInterface", "New Username:"))
        self.newpw.setText(_translate("LogInterface", "New Password:"))
        self.registerbtn.setText(_translate("LogInterface", "Register"))
    
class Application01(QtWidgets.QMainWindow):
    def __init__(self):
        super(Application01,self).__init__()
        self.ui =Ui_LogInterface()
        self.ui.setupUi(self) 
def app():
   app=QtWidgets.QApplication(sys.argv)
   win=Application01()
   win.show()
   sys.exit(app.exec_())

app()
