# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\loginscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc


class Ui_LogInterface(object):
    def setupUi(self, LogInterface):
        LogInterface.setObjectName("LogInterface")
        LogInterface.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(LogInterface)
        self.centralwidget.setObjectName("centralwidget")
        self.email = QtWidgets.QLabel(self.centralwidget)
        self.email.setGeometry(QtCore.QRect(40, 50, 61, 31))
        self.email.setObjectName("email")
        self.password = QtWidgets.QLabel(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(40, 100, 61, 31))
        self.password.setObjectName("password")
        self.unenter = QtWidgets.QLineEdit(self.centralwidget)
        self.unenter.setGeometry(QtCore.QRect(110, 60, 171, 20))
        self.unenter.setObjectName("unenter")
        self.pwenter = QtWidgets.QLineEdit(self.centralwidget)
        self.pwenter.setGeometry(QtCore.QRect(110, 110, 171, 20))
        self.pwenter.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwenter.setObjectName("pwenter")
        self.loginbttn = QtWidgets.QPushButton(self.centralwidget)
        self.loginbttn.setGeometry(QtCore.QRect(110, 160, 111, 41))
        self.loginbttn.setObjectName("loginbttn")
        self.loginbttn.clicked.connect(self.login)
        self.createlabel = QtWidgets.QLabel(self.centralwidget)
        self.createlabel.setGeometry(QtCore.QRect(380, 10, 241, 31))
        self.createlabel.setObjectName("createlabel")
        self.userlabel = QtWidgets.QLabel(self.centralwidget)
        self.userlabel.setGeometry(QtCore.QRect(10, 10, 291, 31))
        self.userlabel.setObjectName("userlabel")
        self.newemail = QtWidgets.QLabel(self.centralwidget)
        self.newemail.setGeometry(QtCore.QRect(310, 50, 81, 31))
        self.newemail.setObjectName("newemail")
        self.newpw = QtWidgets.QLabel(self.centralwidget)
        self.newpw.setGeometry(QtCore.QRect(310, 100, 81, 31))
        self.newpw.setObjectName("newpw")
        self.newpwenter = QtWidgets.QLineEdit(self.centralwidget)
        self.newpwenter.setGeometry(QtCore.QRect(420, 110, 201, 20))
        self.newpwenter.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newpwenter.setObjectName("newpwenter")
        self.newunenter = QtWidgets.QLineEdit(self.centralwidget)
        self.newunenter.setGeometry(QtCore.QRect(420, 60, 201, 20))
        self.newunenter.setObjectName("newunenter")
        self.registerbtn = QtWidgets.QPushButton(self.centralwidget)
        self.registerbtn.setGeometry(QtCore.QRect(390, 160, 111, 41))
        self.registerbtn.setObjectName("registerbtn")
        self.labelResult = QtWidgets.QLabel(self.centralwidget)
        self.labelResult.setGeometry(QtCore.QRect(110, 210, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelResult.setFont(font)
        self.labelResult.setObjectName("labelResult")
        LogInterface.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LogInterface)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        LogInterface.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LogInterface)
        self.statusbar.setObjectName("statusbar")
        LogInterface.setStatusBar(self.statusbar)

        self.retranslateUi(LogInterface)
        QtCore.QMetaObject.connectSlotsByName(LogInterface)
    
    def login(self):
        try:
            email=self.unenter.text()
            password=self.pwenter.text()

            mydb=mc.connect(
                host="localhost",
                user="root",
                password="Efehan33!",
                database="libraryprogram"

            )
 
            mycursor=mydb.cursor()
            query = "SELECT email,password from users where email " "like '"+email + "'and password like '"  + password + "'"
            mycursor.execute(query)
            result=mycursor.fetchone()

            if result ==None:
                self.labelResult.setText("Incorrect email and password")

            else:
                self.labelResult.setText("You are logged in")           

        except mc.Error as e:
            self.labelResult.setText("Error")

    def retranslateUi(self, LogInterface):
        _translate = QtCore.QCoreApplication.translate
        LogInterface.setWindowTitle(_translate("LogInterface", "MainWindow"))
        self.email.setText(_translate("LogInterface", "Email:"))
        self.password.setText(_translate("LogInterface", "Password:"))
        self.loginbttn.setText(_translate("LogInterface", "Login "))
        self.createlabel.setText(_translate("LogInterface", "Create an account if you don\'t have"))
        self.userlabel.setText(_translate("LogInterface", "If you have an account enter your username and password"))
        self.newemail.setText(_translate("LogInterface", "New Email:"))
        self.newpw.setText(_translate("LogInterface", "New Password:"))
        self.registerbtn.setText(_translate("LogInterface", "Register"))
        self.labelResult.setText(_translate("LogInterface", "Result"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LogInterface = QtWidgets.QMainWindow()
    ui = Ui_LogInterface()
    ui.setupUi(LogInterface)
    LogInterface.show()
    sys.exit(app.exec_())
